export interface OpenFile {
  uri: string;          // vscode.Uri.toString()
  cursorLine: number;
  cursorCharacter: number;
  scrollTop: number;    // visible range start line
  viewColumn: number;   // 1 = left, 2 = right, etc.
}

export interface GitContext {
  branch: string;
  recentCommits: string[];   // "abc1234 commit message"
  diffStat: string;          // "+42 -18 across 3 files"
  stagedFiles: string[];
}

export interface TerminalContext {
  cwd: string;
  lastCommands: string[];    // best-effort, may be empty
}

export interface FocusSession {
  id: string;                // crypto.randomUUID()
  name: string;              // user-provided or auto-generated
  workspaceRoot: string;     // absolute path
  createdAt: string;         // ISO 8601
  editor: {
    openFiles: OpenFile[];
    activeFileUri: string;
    splitLayout: string;     // "single" | "two-columns" | "three-columns"
  };
  git: GitContext;
  terminal: TerminalContext;
  aiSummary: string;         // generated by Groq (Llama 3.3 70B)
  cursorContext: string;     // raw ~50 lines around cursor, used as AI input
}